// Generated by gencpp from file nlosExclusion/DOP.msg
// DO NOT EDIT!


#ifndef NLOSEXCLUSION_MESSAGE_DOP_H
#define NLOSEXCLUSION_MESSAGE_DOP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nlosExclusion
{
template <class ContainerAllocator>
struct DOP_
{
  typedef DOP_<ContainerAllocator> Type;

  DOP_()
    : header()
    , HDOP(0.0)
    , VDOP(0.0)
    , DOP(0.0)  {
    }
  DOP_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , HDOP(0.0)
    , VDOP(0.0)
    , DOP(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _HDOP_type;
  _HDOP_type HDOP;

   typedef double _VDOP_type;
  _VDOP_type VDOP;

   typedef double _DOP_type;
  _DOP_type DOP;





  typedef boost::shared_ptr< ::nlosExclusion::DOP_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlosExclusion::DOP_<ContainerAllocator> const> ConstPtr;

}; // struct DOP_

typedef ::nlosExclusion::DOP_<std::allocator<void> > DOP;

typedef boost::shared_ptr< ::nlosExclusion::DOP > DOPPtr;
typedef boost::shared_ptr< ::nlosExclusion::DOP const> DOPConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlosExclusion::DOP_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlosExclusion::DOP_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlosExclusion::DOP_<ContainerAllocator1> & lhs, const ::nlosExclusion::DOP_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.HDOP == rhs.HDOP &&
    lhs.VDOP == rhs.VDOP &&
    lhs.DOP == rhs.DOP;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlosExclusion::DOP_<ContainerAllocator1> & lhs, const ::nlosExclusion::DOP_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlosExclusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::DOP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::DOP_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::DOP_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::DOP_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::DOP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::DOP_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlosExclusion::DOP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3952c03502d92a32dab2225115d9ad47";
  }

  static const char* value(const ::nlosExclusion::DOP_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3952c03502d92a32ULL;
  static const uint64_t static_value2 = 0xdab2225115d9ad47ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlosExclusion::DOP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlosExclusion/DOP";
  }

  static const char* value(const ::nlosExclusion::DOP_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlosExclusion::DOP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 HDOP\n"
"float64 VDOP\n"
"float64 DOP\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nlosExclusion::DOP_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlosExclusion::DOP_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.HDOP);
      stream.next(m.VDOP);
      stream.next(m.DOP);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DOP_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlosExclusion::DOP_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlosExclusion::DOP_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "HDOP: ";
    Printer<double>::stream(s, indent + "  ", v.HDOP);
    s << indent << "VDOP: ";
    Printer<double>::stream(s, indent + "  ", v.VDOP);
    s << indent << "DOP: ";
    Printer<double>::stream(s, indent + "  ", v.DOP);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLOSEXCLUSION_MESSAGE_DOP_H
