// Generated by gencpp from file nlosExclusion/Error.msg
// DO NOT EDIT!


#ifndef NLOSEXCLUSION_MESSAGE_ERROR_H
#define NLOSEXCLUSION_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nlosExclusion
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : header()
    , errorxyz(0.0)
    , errorxy(0.0)  {
    }
  Error_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , errorxyz(0.0)
    , errorxy(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _errorxyz_type;
  _errorxyz_type errorxyz;

   typedef double _errorxy_type;
  _errorxy_type errorxy;





  typedef boost::shared_ptr< ::nlosExclusion::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlosExclusion::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::nlosExclusion::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::nlosExclusion::Error > ErrorPtr;
typedef boost::shared_ptr< ::nlosExclusion::Error const> ErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlosExclusion::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlosExclusion::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlosExclusion::Error_<ContainerAllocator1> & lhs, const ::nlosExclusion::Error_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.errorxyz == rhs.errorxyz &&
    lhs.errorxy == rhs.errorxy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlosExclusion::Error_<ContainerAllocator1> & lhs, const ::nlosExclusion::Error_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlosExclusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::Error_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::Error_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlosExclusion::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d5b1bfb6782c1936ae02bf67d802292";
  }

  static const char* value(const ::nlosExclusion::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d5b1bfb6782c193ULL;
  static const uint64_t static_value2 = 0x6ae02bf67d802292ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlosExclusion::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlosExclusion/Error";
  }

  static const char* value(const ::nlosExclusion::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlosExclusion::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 errorxyz\n"
"float64 errorxy\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nlosExclusion::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlosExclusion::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.errorxyz);
      stream.next(m.errorxy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlosExclusion::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlosExclusion::Error_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "errorxyz: ";
    Printer<double>::stream(s, indent + "  ", v.errorxyz);
    s << indent << "errorxy: ";
    Printer<double>::stream(s, indent + "  ", v.errorxy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLOSEXCLUSION_MESSAGE_ERROR_H
