// Generated by gencpp from file nlosExclusion/exclusionSatNum.msg
// DO NOT EDIT!


#ifndef NLOSEXCLUSION_MESSAGE_EXCLUSIONSATNUM_H
#define NLOSEXCLUSION_MESSAGE_EXCLUSIONSATNUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nlosExclusion
{
template <class ContainerAllocator>
struct exclusionSatNum_
{
  typedef exclusionSatNum_<ContainerAllocator> Type;

  exclusionSatNum_()
    : header()
    , satlist()
    , totalSat(0.0)  {
    }
  exclusionSatNum_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , satlist(_alloc)
    , totalSat(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _satlist_type;
  _satlist_type satlist;

   typedef double _totalSat_type;
  _totalSat_type totalSat;





  typedef boost::shared_ptr< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> const> ConstPtr;

}; // struct exclusionSatNum_

typedef ::nlosExclusion::exclusionSatNum_<std::allocator<void> > exclusionSatNum;

typedef boost::shared_ptr< ::nlosExclusion::exclusionSatNum > exclusionSatNumPtr;
typedef boost::shared_ptr< ::nlosExclusion::exclusionSatNum const> exclusionSatNumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlosExclusion::exclusionSatNum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlosExclusion::exclusionSatNum_<ContainerAllocator1> & lhs, const ::nlosExclusion::exclusionSatNum_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.satlist == rhs.satlist &&
    lhs.totalSat == rhs.totalSat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlosExclusion::exclusionSatNum_<ContainerAllocator1> & lhs, const ::nlosExclusion::exclusionSatNum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlosExclusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ac28900d61bd1d2d33208fbe58e703f";
  }

  static const char* value(const ::nlosExclusion::exclusionSatNum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ac28900d61bd1d2ULL;
  static const uint64_t static_value2 = 0xd33208fbe58e703fULL;
};

template<class ContainerAllocator>
struct DataType< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlosExclusion/exclusionSatNum";
  }

  static const char* value(const ::nlosExclusion::exclusionSatNum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] satlist\n"
"float64 totalSat\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nlosExclusion::exclusionSatNum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.satlist);
      stream.next(m.totalSat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct exclusionSatNum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlosExclusion::exclusionSatNum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlosExclusion::exclusionSatNum_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "satlist[]" << std::endl;
    for (size_t i = 0; i < v.satlist.size(); ++i)
    {
      s << indent << "  satlist[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.satlist[i]);
    }
    s << indent << "totalSat: ";
    Printer<double>::stream(s, indent + "  ", v.totalSat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLOSEXCLUSION_MESSAGE_EXCLUSIONSATNUM_H
